import React from "react";
import {
  useGetAiInsights,
  useAnalyzeAiInsights,
  useAcceptAiInsight,
  useDismissAiInsight,
  getGetAiInsightsQueryKey,
  getGetAiInsightsOverviewQueryKey,
  type AiInsight,
} from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, RefreshCw, Check, X, Info, ShieldCheck, Cpu } from "lucide-react";

type EntityType = "lead" | "contact" | "organization";

const INSIGHT_LABELS: Record<string, string> = {
  lead_intelligence: "Lead Intelligence",
  company_intelligence: "Company Intelligence",
  contact_intelligence: "Contact Intelligence",
  smart_classification: "Smart Classification",
  opportunity_potential: "Opportunity Potential",
  missing_info: "Data Completeness",
  duplicate_intelligence: "Duplicate Detection",
  relationship_intelligence: "Relationship Intelligence",
};

function humanizeKey(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function formatTs(ts?: string | null): string {
  if (!ts) return "—";
  const d = new Date(ts);
  if (isNaN(d.getTime())) return String(ts);
  return d.toLocaleString();
}

function confidenceTone(confidence?: number | null): string {
  if (confidence === null || confidence === undefined) return "bg-muted text-muted-foreground";
  if (confidence >= 80) return "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300";
  if (confidence >= 60) return "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300";
  return "bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300";
}

function ScalarValue({ value }: { value: unknown }) {
  if (value === null || value === undefined || value === "") {
    return <span className="text-muted-foreground">—</span>;
  }
  if (typeof value === "boolean") {
    return <span>{value ? "Yes" : "No"}</span>;
  }
  return <span>{String(value)}</span>;
}

function DataValue({ value }: { value: unknown }) {
  if (Array.isArray(value)) {
    if (value.length === 0) return <span className="text-muted-foreground">None</span>;
    return (
      <ul className="space-y-1 mt-1">
        {value.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm">
            <div className="w-1 h-1 rounded-full bg-primary mt-1.5 flex-shrink-0" />
            {item !== null && typeof item === "object" ? (
              <div className="space-y-0.5">
                {Object.entries(item as Record<string, unknown>).map(([k, v]) => (
                  <div key={k}>
                    <span className="text-muted-foreground">{humanizeKey(k)}: </span>
                    <ScalarValue value={v} />
                  </div>
                ))}
              </div>
            ) : (
              <ScalarValue value={item} />
            )}
          </li>
        ))}
      </ul>
    );
  }
  if (value !== null && typeof value === "object") {
    return (
      <div className="space-y-0.5 mt-1">
        {Object.entries(value as Record<string, unknown>).map(([k, v]) => (
          <div key={k} className="text-sm">
            <span className="text-muted-foreground">{humanizeKey(k)}: </span>
            <ScalarValue value={v} />
          </div>
        ))}
      </div>
    );
  }
  return <ScalarValue value={value} />;
}

function InsightCard({
  insight,
  onAccept,
  onDismiss,
  acting,
}: {
  insight: AiInsight;
  onAccept: (id: number) => void;
  onDismiss: (id: number) => void;
  acting: boolean;
}) {
  const label = INSIGHT_LABELS[insight.insightType] ?? humanizeKey(insight.insightType);
  const isDeterministic = insight.source === "deterministic";
  const dataEntries = Object.entries(insight.data ?? {}).filter(
    ([, v]) => v !== null && v !== undefined,
  );

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-start justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <span className="font-medium text-sm">{label}</span>
          <Badge
            variant="outline"
            className="text-[10px] gap-1 font-normal"
            title={isDeterministic ? "Computed from your CRM data (no AI)" : "Generated by AI from your CRM data"}
          >
            {isDeterministic ? <ShieldCheck className="h-3 w-3" /> : <Cpu className="h-3 w-3" />}
            {isDeterministic ? "Rule-based" : "AI"}
          </Badge>
          <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full ${confidenceTone(insight.confidence)}`}>
            {insight.confidence === null || insight.confidence === undefined
              ? "Confidence n/a"
              : `${insight.confidence}% confidence`}
          </span>
        </div>
        {insight.status === "suggested" ? null : (
          <Badge variant={insight.status === "accepted" ? "default" : "secondary"} className="capitalize text-[10px]">
            {insight.status}
          </Badge>
        )}
      </div>

      {insight.reasoning && (
        <p className="text-sm leading-relaxed text-foreground/90">{insight.reasoning}</p>
      )}

      {dataEntries.length > 0 && (
        <div className="space-y-2">
          {dataEntries.map(([key, value]) => (
            <div key={key}>
              <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                {humanizeKey(key)}
              </p>
              <DataValue value={value} />
            </div>
          ))}
        </div>
      )}

      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground pt-1 border-t border-border/60">
        <span>Analyzed {formatTs(insight.lastAnalysisAt ?? insight.generatedAt)}</span>
        {!isDeterministic && insight.model && <span>Model: {insight.model}</span>}
        {insight.promptVersion !== null && insight.promptVersion !== undefined && (
          <span>Prompt v{insight.promptVersion}</span>
        )}
        {insight.status === "accepted" && insight.acceptedAt && (
          <span>Accepted {formatTs(insight.acceptedAt)}</span>
        )}
      </div>

      {insight.status === "suggested" && (
        <div className="flex items-center gap-2 pt-1">
          <Button size="sm" onClick={() => onAccept(insight.id)} disabled={acting} className="gap-1">
            <Check className="h-3.5 w-3.5" /> Accept
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => onDismiss(insight.id)}
            disabled={acting}
            className="gap-1"
          >
            <X className="h-3.5 w-3.5" /> Dismiss
          </Button>
        </div>
      )}
    </div>
  );
}

export function AiInsightsPanel({
  entityType,
  id,
}: {
  entityType: EntityType;
  id: number;
}) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { data, isLoading } = useGetAiInsights(entityType, id, {
    query: { queryKey: getGetAiInsightsQueryKey(entityType, id), enabled: id > 0 },
  });
  const analyze = useAnalyzeAiInsights();
  const accept = useAcceptAiInsight();
  const dismiss = useDismissAiInsight();

  const insights = data?.insights ?? [];

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: getGetAiInsightsQueryKey(entityType, id) });
    queryClient.invalidateQueries({ queryKey: getGetAiInsightsOverviewQueryKey() });
  };

  const handleAnalyze = () => {
    analyze.mutate(
      { entityType, id },
      {
        onSuccess: (res) => {
          invalidate();
          const errs = res.aiErrors ?? [];
          if (errs.length > 0) {
            toast({
              title: "Analysis completed with warnings",
              description: `${errs.length} AI feature(s) could not run and were skipped.`,
              variant: "destructive",
            });
          } else {
            toast({ title: "AI analysis updated" });
          }
        },
        onError: () => {
          toast({ title: "Analysis failed", description: "Please try again.", variant: "destructive" });
        },
      },
    );
  };

  const handleAccept = (insightId: number) => {
    accept.mutate(
      { id: insightId },
      {
        onSuccess: () => {
          invalidate();
          toast({ title: "Recommendation accepted" });
        },
        onError: () => toast({ title: "Could not accept", variant: "destructive" }),
      },
    );
  };

  const handleDismiss = (insightId: number) => {
    dismiss.mutate(
      { id: insightId },
      {
        onSuccess: () => {
          invalidate();
          toast({ title: "Recommendation dismissed" });
        },
        onError: () => toast({ title: "Could not dismiss", variant: "destructive" }),
      },
    );
  };

  const acting = accept.isPending || dismiss.isPending;

  return (
    <Card className="shadow-sm border-primary/20">
      <CardHeader className="pb-3 border-b border-primary/10">
        <div className="flex items-center justify-between gap-2">
          <CardTitle className="text-base flex items-center gap-2 text-primary">
            <Sparkles className="h-4 w-4" /> AI Insights
          </CardTitle>
          <Button size="sm" variant="outline" onClick={handleAnalyze} disabled={analyze.isPending} className="gap-1">
            <RefreshCw className={`h-3.5 w-3.5 ${analyze.isPending ? "animate-spin" : ""}`} />
            {insights.length > 0 ? "Re-analyze" : "Analyze"}
          </Button>
        </div>
      </CardHeader>
      <CardContent className="pt-4 space-y-3">
        {isLoading ? (
          <p className="text-sm text-muted-foreground">Loading insights…</p>
        ) : insights.length === 0 ? (
          <div className="flex items-start gap-2 text-sm text-muted-foreground">
            <Info className="h-4 w-4 mt-0.5 flex-shrink-0" />
            <span>
              No AI insights yet. Run an analysis to generate recommendations from this record's CRM data. All
              recommendations stay reviewable and are never applied automatically.
            </span>
          </div>
        ) : (
          insights.map((insight) => (
            <InsightCard
              key={insight.id}
              insight={insight}
              onAccept={handleAccept}
              onDismiss={handleDismiss}
              acting={acting}
            />
          ))
        )}
      </CardContent>
    </Card>
  );
}

export default AiInsightsPanel;
